Cypress.Commands.add('fillMandatoryFieldsAndSubmit', () => {
    cy.get('#firstName').type('Brian Mucio')
        cy.get('#lastName').type('Duarte')
        cy.get('#email').type('braianmucioduarte@gmail.com')
        cy.get('#phone').type('973571449')
        cy.get('#product').select('Mentoria')
        cy.get('input[type="radio"][value="feedback"]').click()
        cy.get('input[type="checkbox"][value="email"]').click()
        cy.get('#open-text-area').type('O curso é excelente!')
        cy.get('button[type="submit"]').click()
})